{% set name = "cached_interpolate" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cached_interpolate-{{ version }}.tar.gz
  sha256: 8c8dcd705af8d5dae97bfcb48c5e6359cbccb365edcba458f135e2c8daac3114

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  imports:
    - cached_interpolate
    - cached_interpolate.build
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColmTalbot/cached_interpolation
  summary: Efficient repeated evaluation of splines at fixed points.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
